### PR TITLE
feat: Link items from Nightly Spurious Failures table to history view

### PR DESCRIPTION
**Pull request by lluiscampos**

### CODE REVIEW

**Comment by lluiscampos** [comment]
I am submitting this PR blindly :see_no_evil:

I was not able to build the `ui` Docker image without the secrets - how do you guys do it?

**Comment by oleorhagen** [comment]
> I am submitting this PR blindly see_no_evil
> 
> I was not able to build the `ui` Docker image without the secrets - how do you guys do it?

Nice! I see you got around to doing it :muscle: 

Pr looks good to me. Two minor issues I see:

* Missing import:

```
diff --git a/ui/src/statistics/spurious-failures-view.js b/ui/src/statistics/spurious-failures-view.js
index ee4935c..c48351b 100644
--- a/ui/src/statistics/spurious-failures-view.js
+++ b/ui/src/statistics/spurious-failures-view.js
@@ -6,6 +6,8 @@ import { AdapterDayjs } from '@mui/x-date-pickers/AdapterDayjs';
 import { DesktopDatePicker } from '@mui/x-date-pickers/DesktopDatePicker';
 import { DataGrid } from '@mui/x-data-grid';
 
+import Link from '../../components/link';
+
 import dayjs from 'dayjs';
 
 const columns = [
```

* Link in the history view is missing the `project`(?) I think: http://localhost/projects/undefined/tests/history?name=tests.test_filetransfer.TestFileTransferLegacyClientOS.test_filetransfer_not_implemented&count=10

Oh, and there's not that hard to get it up:

```
docker-compose -f docker-compose.yml -f development.yml up
```

With this in my environment:

```
export TETRA_USER=test
export TETRA_PASSWORD=test
export GITLAB_TOKEN="$(pass show private/gitlab/access-token)"
```

**Comment by lluiscampos** [comment]
I don't think I will continue on this. Closing for now.

**Comment by oleorhagen** [comment]
Shame, it was close, no? :)

**Pull request closed without merging**
